#!/bin/bash

#  This file is part of Atarashii.
#
#  Atarashii is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Atarashii is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License along with
#  Atarashii. If not, see <http://www.gnu.org/licenses/>.


# Atarashii Crash Wrapper ------------------------------------------------------
# ------------------------------------------------------------------------------

# Catch SIGTERM
STOPPED=false
trap logout_shutdown 15

logout_shutdown() {
    echo "15" >~/Desktop/term.info
    $STOPPED=true
}

# Start Atarashii
RESTART=0
CODE=0
echo "Starting Atarashii..."
while [ $RESTART -lt 3 ]
do
    # Start
    ./debug.py
    
    # Varas
    let CODE=$?
    let RESTART=RESTART+1
    
    # Checks
    if [ $CODE -eq 0 ]; then
        echo "Atarashii has exited normally."
        exit 0
    
    elif [ $CODE -eq 69 ]; then
        echo "Atarashii is alreay running."
        exit 0
    
    elif [ $CODE -eq 70 ]; then
        echo "70" >~/.atarashii/crash.log
        echo "Atarashii crashed due to an internal error!"
        echo "Restarting..."
    
    elif [ $CODE -eq 75 ]; then
        echo "Atarashii could not be started!"
        exit 2
    
    elif [ $CODE -eq -9 ]; then
        echo "Atarashii has been killed."
        exit 1
    
    elif [ $CODE -eq -15 ]; then
        echo "Atarashii has been terminated."
        exit 1
    
    elif [ ! $STOPPED ]; then
        echo $? >~/.atarashii/crash.log
        echo "Atarashii crashed due to an external error!"
        echo "Restarting..."
    fi
done

