#!/bin/sh
#  This file is part of Atarashii.
#
#  Atarashii is free software: you can redistribute it and/or
#  modify it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Atarashii is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
# 
#  You should have received a copy of the GNU General Public License along with
#  Atarashii. If not, see <http://www.gnu.org/licenses/>.

# Exit on error!
set -e


# Add repository ---------------------------------------------------------------
# ------------------------------------------------------------------------------
REPO_FILE=/etc/apt/sources.list.d/atarashii.list
REPO="deb http://bonsaiden.github.com/Atarashii /"

# Create the repo file
echo "Checking for repository file..."
if [ -e $REPO_FILE ]; then
    DATA=$(cat $REPO_FILE)
    if [ "$DATA" = "$REPO" ]; then
        echo "File found and up to date! Doing nothing."
        
    else
        echo "File found but contents are invalid! Removing..."
        rm $REPO_FILE
        
        echo "Creating new file..."
        touch $REPO_FILE
        echo $REPO >> $REPO_FILE
        
        echo "Done!"
    fi
else 
    echo "File not Found. Creating new one..."
    touch $REPO_FILE
    echo $REPO >> $REPO_FILE
    
    echo "Done!"
fi

# Install key
KEY_BIN="`which apt-key 2> /dev/null`"
if [ -x "$KEY_BIN" ]; then
    echo "Installing public key..."
    "$KEY_BIN" add - >/dev/null 2>&1 <<KEYDATA
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.9 (GNU/Linux)

mQGiBEulVDARBACVBpOl2He8VY9w4Rf+yPfWsbMq+5neGm9cdJlQxar89KyEnEIL
8zfEDymt3qW+NaJICOIgnJA5KAA3Tvl1gzslQUHgWR+ECvXdhH4Vllhe/byQF5xp
oludbHCsIHGLDS6na3ZSd71vTHWlUdfK/bp6MMey1uE0ZI4zKcVopTPvmwCgrvF2
Her6UI3j5ecvBDlx7hgRhkcD/jVS2cZcT7WUGIMLviM8sGVim3wCGsyXGo3SxZXA
4PMcIpqiY0V/35L39qm3X7q9MdbtBYOm/Wr7oGjimVzLgQTAFLBdGElUa7tehHKG
Xtcsdf9XnHZQCo6lC/OrO6i1h0082ltT0hpgMSz2zFh92IefAzSwYpKAGFakdqWZ
VJDBA/9CwsF6GGP+1euiiLtqSyBl813B4ULYrEpxaZMfINXp4XsjRizeP0MPCJtn
tG7g3SRaj2lvnCd3QIPrI5k8ur7iB9qABWK85zoqwILGu9koit5VDqUobScUg/Rf
IbtDEGUxEqueiWQlYHVZzpotZ6LZP2f8p0si+SVDhCHhZzGZ2rQwSXZvIFdldHpl
bCAoR1BHIEtleSkgPGl2by53ZXR6ZWxAZ29vZ2xlbWFpbC5jb20+iGAEExECACAF
AkulVDACGwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRCdfYMKVtJbHh8vAJ48
CdEWqbJI3eTsLNyWWAwX62IGbQCeM8Rs1AP3SGXoh3PJbVea2shPK3C5AQ0ES6VU
MBAEANWCWmrzNVGabxEDK96w+np2jXORu58GePlGXqqqYH7dydyUohbQjXGnrdqr
pyptOgXW6y74osSk08ufNr4jBwhpab8RD5fBVPNX6lVsYJjzETP1D4JUsASSpwzH
05WWhOiixB58T0DdN7L/Wt/Kkf62K3vYOSnPKSCvuT4C8cwDAAMGBACPF80WG5tD
ugi1NhC8sDJUVcwCnoWwvK7ymuIGPw1U0yz8EUL3Ksjd7J7Neiw3Ci0u006f90fY
j+dMU3y0PYA9gNnHZoejVffKDmgrVvfxloNw8TdzvU9m1vz8/H6c6DzH0hGoFFRh
BVV0jKRQPr9dZ12dUNwRSV+VvkanigQw94hJBBgRAgAJBQJLpVQwAhsMAAoJEJ19
gwpW0lsetgEAmwU6Jx52n/HuKvsjMHE88XGUCUpkAKCU+DEomo9DKMHBwpSINWX4
09dB6w==
=xJLG
-----END PGP PUBLIC KEY BLOCK-----
KEYDATA
    echo "Done!"
fi

# Install icon
ICON_FILE="/usr/share/icons/atarashii.png"
ICON="`which xdg-icon-resource 2> /dev/null`"
if [ -x "$ICON" ]; then
    "$ICON" install --size "128" "$ICON_FILE" "bonsaiden-atarashii"
    echo "Installed icon!"
fi

